### ISSUE TITLE
500 SQLSTATE Error when navigating to Edit initiatives from Admin Tools

### ISSUE THREAD

**Issue by emlanctot** [suma-project/Suma#84]
After logging into the Admin interface and clicking on "Edit initiatives" I get the following 500 error:
> 500 Internal Server Error
> SQLSTATE[HY000] [2002] Connection refused

Earlier I was getting this: 
> 500 Internal Server Error
> The mysql driver is not currently installed.

I was able to fix this by enabling `extension=php_pdo_mysql.dll` in my php.ini file.

But now I'm getting hung up on this `SQLSTATE[HY000] [2002]` error and I haven't been able to find out too much information about a way to resolve this. I'm running this on a Debian server.

Does anyone know what might be going wrong here?

**Comment by kbeswick** [comment]
Looks like Suma is not able to connect to your MySQL database - I'd start by double checking the database connection information in <SUMA_SERVER_INSTALL_DIR>/config/config.yaml , including making sure the port number is correct (default port for MySQL is 3306, but it may be listening on a different port on your server). If you aren't sure what port MySQL running on, there are some suggestions here that might help: https://serverfault.com/questions/116100/how-to-check-what-port-mysql-is-running-on

Let me know if this helps!

**Comment by emlanctot** [comment]
I just double checked both of these values and it looks like they should be talking:
```
SHOW GLOBAL VARIABLES LIKE 'PORT';
+---------------+-------+
| Variable_name | Value |
+---------------+-------+
| port          | 3306  |
+---------------+-------+
```
and in `/var/www/app/sumaserver/config`:
```
production:
    sumaserver:
        db:
            host: ***
            platform: Pdo_Mysql
            dbname: suma_prod
            user: ***
            pword: ***
            port: 3306
```
